### ISSUE TITLE
Check error handling for non-existant ObjectIds

### ISSUE THREAD

**Issue by benburwell** [benburwell/MCEMS-Site#20]
E.g. http://www.bergems.org/members/edit/51f426655c17070200000001

**Comment by benburwell** [comment]
When you're logged in with edit members permission and you visit this link, the app will crash.

**Comment by jmankhan** [comment]
I'll check it out, I've been having some trouble with mongo inside vagrant, but once I get it sorted out, I'll start working on it

**Comment by jmankhan** [comment]
Now checks for null members, and redirects to main page if member is not found
