### ISSUE TITLE
Make waiver checkboxes

### ISSUE THREAD

**Issue by benburwell** [benburwell/MCEMS-Site#29]
In order to keep track of which members have submitted the following information, add checkboxes to the member detail view to reflect whether they have signed the following forms:
- Photo release
- ID card
- Uniform
- Bylaws
- Bylaws quiz
- Stairchair
- Stairchair quiz

**Comment by benburwell** [comment]
This should be a pretty simple addition to the Member schema. After that it's pretty much adding more checkboxes to the view and handling them in the controller.

**Comment by benburwell** [comment]
@EliRuss, is this still something you're interested in?

**Comment by EliRuss** [comment]
If it's simple, then yes. Would need to be only updatable by those with permissions to update profiles, not the users themselves.

Forms:
- Photo Release 
- Bylaws/SOP Acknowledgement
- Bylaws/SOPs Quiz
- Stairchair Quiz
- Stairchar Waiver
- Infection Control Waiver
- Uniform Waiver

**Comment by jmankhan** [comment]
I have added the waivers to the member details section. They correctly save, but I am still working on making them only editable by those with edit_member permission. They are currently on the 'waivers' branch

**Comment by benburwell** [comment]
Looks like this is done.
