### ISSUE TITLE
Website logo change

### ISSUE THREAD

**Issue by EliRuss** [benburwell/MCEMS-Site#47]
The website currently has the old logo on it's banner. Can we update is to the current logo? It is available off our Facebook Page, but I can email it to you separately if that does not work. @jmankhan CC: @benburwell

**Comment by EliRuss** [comment]
Just wanted to follow-up, especially considering our logo is not anywhere on the new website.

**Comment by benburwell** [comment]
Thanks. I think I'll close this for now. It hasn't actually been changed on the old website aka now the portal, but I think it's a wontfix at this point.

I haven't put the patch anywhere on the new site except for the favicon. I didn't see a great place to put it; if you'd like me too add it somewhere, open an issue in MCEMS/www

**Comment by EliRuss** [comment]
I don't really care about the Member Portal page. I was thinking putting on on the Contact page.
